language: java

jdk:
  - oraclejdk11
  
#before_install:
  #  export CLASSPATH=./src/junit-4.13.jar:hamcrest-core-1.3.jar
#install:
 #   echo $CLASSPATH
before_script:
    javac -cp ./src/junit-4.13.jar;. PriorityQueueTest.java 
script:
    java -cp junit-4.13.jar;hamcrest-core-1.3.jar;. org.junit.runner.JUnitCore PriorityQueueTest 

