language: java

jdk:
  - oraclejdk11
  
before_install:
    export CLASSPATH=junit-4.13.jar:hamcrest-core-1.3.jar
install:
    echo $PATH
before_script:
    javac PriorityQueueTest.java
script:
    java PriorityQueueTest
